//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.RecursosLocalizables.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string BtnActualizar {
            get {
                return ResourceManager.GetString("BtnActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string BtnBorrar {
            get {
                return ResourceManager.GetString("BtnBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string BtnBuscar {
            get {
                return ResourceManager.GetString("BtnBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar datos.
        /// </summary>
        public static string BtnCargaEAD {
            get {
                return ResourceManager.GetString("BtnCargaEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar datos.
        /// </summary>
        public static string BtnCargaLGD {
            get {
                return ResourceManager.GetString("BtnCargaLGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar datos.
        /// </summary>
        public static string BtnCargaPD {
            get {
                return ResourceManager.GetString("BtnCargaPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ente.
        /// </summary>
        public static string BtnFiltroEnteCliente {
            get {
                return ResourceManager.GetString("BtnFiltroEnteCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string BtnFiltroIdCliente {
            get {
                return ResourceManager.GetString("BtnFiltroIdCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Cliente.
        /// </summary>
        public static string BtnFiltroNombreCliente {
            get {
                return ResourceManager.GetString("BtnFiltroNombreCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrumento (origen).
        /// </summary>
        public static string BtnFiltroSistemaOrigen {
            get {
                return ResourceManager.GetString("BtnFiltroSistemaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string BtnIniciarSesion {
            get {
                return ResourceManager.GetString("BtnIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string BtnInicio {
            get {
                return ResourceManager.GetString("BtnInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrás.
        /// </summary>
        public static string BtnRegresar {
            get {
                return ResourceManager.GetString("BtnRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error. Por favor contactar a soporte técnico con el siguiente código.
        /// </summary>
        public static string ErrorInesperado {
            get {
                return ResourceManager.GetString("ErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LblLoginContrasena {
            get {
                return ResourceManager.GetString("LblLoginContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string LblLoginUsuario {
            get {
                return ResourceManager.GetString("LblLoginUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bancas.
        /// </summary>
        public static string LblMenuBanca {
            get {
                return ResourceManager.GetString("LblMenuBanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extracciones.
        /// </summary>
        public static string LblMenuCalculos {
            get {
                return ResourceManager.GetString("LblMenuCalculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envío de datos.
        /// </summary>
        public static string LblMenuCargaDatos {
            get {
                return ResourceManager.GetString("LblMenuCargaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogos.
        /// </summary>
        public static string LblMenuCatalogos {
            get {
                return ResourceManager.GetString("LblMenuCatalogos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañías.
        /// </summary>
        public static string LblMenuCompania {
            get {
                return ResourceManager.GetString("LblMenuCompania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EAD.
        /// </summary>
        public static string LblMenuEAD {
            get {
                return ResourceManager.GetString("LblMenuEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LGD.
        /// </summary>
        public static string LblMenuLGD {
            get {
                return ResourceManager.GetString("LblMenuLGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañía.
        /// </summary>
        public static string LblMenuMantCompania {
            get {
                return ResourceManager.GetString("LblMenuMantCompania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correos.
        /// </summary>
        public static string LblMenuMantCorreo {
            get {
                return ResourceManager.GetString("LblMenuMantCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimientos.
        /// </summary>
        public static string LblMenuMantenimientos {
            get {
                return ResourceManager.GetString("LblMenuMantenimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segmento.
        /// </summary>
        public static string LblMenuMantSegmentos {
            get {
                return ResourceManager.GetString("LblMenuMantSegmentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tratamiento.
        /// </summary>
        public static string LblMenuMantTratamiento {
            get {
                return ResourceManager.GetString("LblMenuMantTratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auditoría.
        /// </summary>
        public static string LblMenuModificaciones {
            get {
                return ResourceManager.GetString("LblMenuModificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PD.
        /// </summary>
        public static string LblMenuPD {
            get {
                return ResourceManager.GetString("LblMenuPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segmentos.
        /// </summary>
        public static string LblMenuSegmentos {
            get {
                return ResourceManager.GetString("LblMenuSegmentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin segmento.
        /// </summary>
        public static string LblMenuSinSegmentos {
            get {
                return ResourceManager.GetString("LblMenuSinSegmentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistemas.
        /// </summary>
        public static string LblMenuSistemas {
            get {
                return ResourceManager.GetString("LblMenuSistemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tratamientos.
        /// </summary>
        public static string LblMenuTratamiento {
            get {
                return ResourceManager.GetString("LblMenuTratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NIIF 09 - Revisión de datos.
        /// </summary>
        public static string LoginTitulo {
            get {
                return ResourceManager.GetString("LoginTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario o Contraseña inválida..
        /// </summary>
        public static string MsgUsuarioInvalido {
            get {
                return ResourceManager.GetString("MsgUsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string SubMenuCerrarSesion {
            get {
                return ResourceManager.GetString("SubMenuCerrarSesion", resourceCulture);
            }
        }
    }
}
